### ISSUE TITLE
why did open shift restart app suddenly 

### ISSUE THREAD

**Issue by sayanee** [sayanee/cosmic#6]
:scream: 

```
2943 at Tue Feb 16 2016 20:50:22 GMT-0500 (EST)
2869 at Tue Feb 16 2016 22:50:22 GMT-0500 (EST)
2805 at Wed Feb 17 2016 00:50:22 GMT-0500 (EST)
2709 at Wed Feb 17 2016 02:50:22 GMT-0500 (EST)

> soil-moisture-sensor@1.0.0 start /var/lib/openshift/secret/app-root/runtime/repo
> node index

App running on 8080
2685 at Wed Feb 17 2016 04:26:22 GMT-0500 (EST)
2641 at Wed Feb 17 2016 06:26:22 GMT-0500 (EST)
2445 at Wed Feb 17 2016 08:26:22 GMT-0500 (EST)
```

![image](https://cloud.githubusercontent.com/assets/413879/13114091/f4e3863a-d5cc-11e5-9eac-ad06ac71a632.png)

**Comment by sayanee** [comment]
Handle error properly:

```
2538 at Fri Feb 19 2016 14:26:25 GMT-0500 (EST)
2520 at Fri Feb 19 2016 16:26:25 GMT-0500 (EST)
undefined:1
<html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.<anonymous> (/var/lib/openshift/secret/app-root/runtime/repo/index.js:32:27)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/lib/openshift/secret/app-root/data/node_modules/request/request.js:960:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:743:26)
    at resume_ (_stream_readable.js:723:3)

npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! argv "/var/lib/openshift/secret/node-four/bin/node/bin/node" "/var/lib/openshift/secret/node-four/bin/node/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! soil-moisture-sensor@1.0.0 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soil-moisture-sensor@1.0.0 start script 'node index'.
npm ERR! This is most likely a problem with the soil-moisture-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls soil-moisture-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/openshift/secret/app-root/runtime/repo/npm-debug.log

> soil-moisture-sensor@1.0.0 start /var/lib/openshift/secret/app-root/runtime/repo
> node index

App running on 8080
2460 at Fri Feb 19 2016 18:52:19 GMT-0500 (EST)
2439 at Fri Feb 19 2016 20:52:19 GMT-0500 (EST)
```

**Comment by sayanee** [comment]
3793c7d64bf1850e36c3dfe1460407e3ca1c224d
